### PR TITLE
Added a 30mins alert/notification before each event created. (by Alert I mean a Reminder)

### PR DESCRIPTION
**Pull request by YBTopaz8**
It bugged me to have an event with no reminder as I forget a lot of stuff 😂

I intend to add some more functionalities like 
- Giving options to add/not add an alert when creating an event.
- Adding an alert from a list of alerts (30mins/1h/2hrs/1Day) then adding an alert with custom time (21mins before, 17hrs before etc)

I think that's it? 😅

### CODE REVIEW

**Comment by YBTopaz8** [comment]
I can see 2 workflows are awaited, i have built the app on my end and it works well on android (since i only edited Android given it being more accessible).
I don't know why the two "builds" are still waiting for status to be reported.. 
If you tell me what to do, then i'd gladly do it in order to have PR approved
thanks for the package ! 😄

**Comment by YBTopaz8** [comment]
Finally managed to push the right commit. 
Sorry for the whole back and forth, it's basically the same thing being repeated

**Comment by carolzbnbr** [comment]
Any chance to push these changes to main?

**Comment by jfversluis** [comment]
I see a couple of weird things happening in here, but let me see if I can clean this up and get it merged :)

**Comment by YBTopaz8** [comment]
I can take some time to redo a pr with a cleaner work? (I was completely noob on GitHub back then, sorry!)

Give me a few please!

**Comment by jfversluis** [comment]
@YBTopaz8 no worries my friend. If you're still interested, then yes please!

I see a couple of files that are being deleted which I don't think should be deleted as well as the .gitignore entries. Otherwise I think it looks alright 😄

**Comment by YBTopaz8** [comment]
Haha, yes. Sure thing!!

Let me retest & brb

**Pull request closed without merging**
